"""add complete academy tables with is_active

Revision ID: 41fef4b59f14
Revises: b4b226b3a68a
Create Date: 2026-02-06 13:22:50.768627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fef4b59f14'
down_revision: Union[str, Sequence[str], None] = 'b4b226b3a68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_info', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('gallery_images', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('gallery_vedio', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'is_active')
    op.drop_column('gallery_vedio', 'is_active')
    op.drop_column('gallery_images', 'is_active')
    op.drop_column('class_info', 'is_active')
    # ### end Alembic commands ###
