"""updatecreat user table

Revision ID: a78e971735ab
Revises: d77e3747acc4
Create Date: 2026-02-07 12:49:53.992810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78e971735ab'
down_revision: Union[str, Sequence[str], None] = 'd77e3747acc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'user_permissions', ['mobile_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='unique')
    op.drop_column('user_permissions', 'mobile_number')
    # ### end Alembic commands ###
