"""add gallery_vedio table

Revision ID: b4b226b3a68a
Revises: 33b5a8f0bcfb
Create Date: 2026-02-06 11:05:28.954164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4b226b3a68a'
down_revision: Union[str, Sequence[str], None] = '33b5a8f0bcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_vedio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_vedio_id'), 'gallery_vedio', ['id'], unique=False)
    op.drop_index(op.f('ix_about_info_id'), table_name='about_info')
    op.drop_table('about_info')
    op.drop_index(op.f('ix_contact_info_id'), table_name='contact_info')
    op.drop_table('contact_info')
    op.alter_column('class_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('class_info', 'age_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('class_info', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('class_info', 'is_active')
    op.alter_column('gallery_images', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('gallery_images', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('gallery_images', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('gallery_images', 'is_active')
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('team_members', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('gallery_images', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('gallery_images', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('gallery_images', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gallery_images', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('class_info', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('class_info', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('class_info', 'age_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('class_info', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('contact_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facebook_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_info_pkey'))
    )
    op.create_index(op.f('ix_contact_info_id'), 'contact_info', ['id'], unique=False)
    op.create_table('about_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('about_info_pkey'))
    )
    op.create_index(op.f('ix_about_info_id'), 'about_info', ['id'], unique=False)
    op.drop_index(op.f('ix_gallery_vedio_id'), table_name='gallery_vedio')
    op.drop_table('gallery_vedio')
    # ### end Alembic commands ###
