"""creat user table

Revision ID: d77e3747acc4
Revises: 41fef4b59f14
Create Date: 2026-02-07 11:51:25.761982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77e3747acc4'
down_revision: Union[str, Sequence[str], None] = '41fef4b59f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('edit', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('upload', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.drop_index(op.f('ix_academy_users_email'), table_name='academy_users')
    op.drop_index(op.f('ix_academy_users_userid'), table_name='academy_users')
    op.drop_index(op.f('ix_academy_users_username'), table_name='academy_users')
    op.drop_table('academy_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy_users',
    sa.Column('userid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('userrole', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userid', name=op.f('academy_users_pkey'))
    )
    op.create_index(op.f('ix_academy_users_username'), 'academy_users', ['username'], unique=True)
    op.create_index(op.f('ix_academy_users_userid'), 'academy_users', ['userid'], unique=False)
    op.create_index(op.f('ix_academy_users_email'), 'academy_users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
